version: "3"
services:
  ultimate-strapi-starter:
    image: postgres:12
    container_name: ultimate-strapi-starter
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
